### ISSUE TITLE
v3.0

### ISSUE THREAD

**Issue by JoshCheek** [JoshCheek/seeing_is_believing#47]
V3 is basically ready at this point. But I'm going to wait until my next break so I can try and make the editor integrations better. I figure a big version bump will get a little bit of attention, so it should be particularly slick when it rolls out. But I spent a lot of time on this (270 commits since I started my break) and want to spend the rest of it on https://github.com/JoshCheek/ruby_object_model_viewer

-----

To accommodate the changes I want, should bump the major version. As long as I'm doing that, might as well stick in a bunch of things I want.

### Code

Code is now on master, see [the commits](https://github.com/JoshCheek/seeing_is_believing/compare/956bd0c...master).
956bd0c..a38fcf4

Lots more stuff happened than is listed here. But I don't think anyone other than me cares about this, so not going to put the effort in to update it.

### Features

* Library
  - [x] Ability to specify in a per-line basis what kind of inspection should be used (basically, allow for the overriding of WrapExpressions keys) [Record inspections by type (e.g. `:inspect` and `:pp`)](https://github.com/JoshCheek/seeing_is_believing/commit/a0e64d34d6018a7192f2dc125c8068c4ef305d07), and [Caller can inject their own expression wrapping](https://github.com/JoshCheek/seeing_is_believing/commit/3ed8083aaa1718d1d73856ae7c0e74ef5a80d3ee).
  - [x] SeeingIsBelieving::VERSION is available to the program (it's something I often want to see). [completed](https://github.com/JoshCheek/seeing_is_believing/commit/e3ad5a7f7bc1bc99900af08a83fe70dec7f3971b)
* Binary
  - [x] Upgrade to latest [Parser](https://github.com/whitequark/parser/)
  - [x] Ability to get an event stream, so that someone could get the events as they occur rather than at the end. Probably emit events each on one-line and in JSON format. Maybe try implementing it in [atom-seeing-is-believing](https://github.com/JoshCheek/atom-seeing-is-believing). 6893b81 
  - [x] Display xmpfilter previous-line annotations with pretty-print (for #44)
  - [x] Deprecate `--shebang` since `RbConfig.ruby` gives the information we needed this for.

### Cleanup

- [x] Generally, tons of stuff happened here. A lot more than is listed.
- [x] Renamings in EventStream + split it out into multiple files
- [x] Rename CleanBody -> RemoveAnnotations
- [x] Refactor that POS AddAnnotations. Probably there are two objects in there, one for sib style, one for xmpfilter style, also, it is annoying that we get the result from AddAnnotations, it conceptually should take a file and a set of results, and add them on each line.
- [x] Make sure I actually like the Result class (I don't particularly, but it solves a relevant issue).
- [x] Probably get rid of the line class (the exception is already on Result, other than that it's just an array) [completed](https://github.com/JoshCheek/seeing_is_believing/commit/4c75ac4d9bcab646444bc5b935cb78ce2b73925e)
- [x] Parser fixed the heredoc bugs, so doesn't need the stupid hacks I wrote. Probably they are littered all over ParserHelpers and WrapExpressions
- [x] Figure out this encoding bullshit (#33) 
- [x] Switch syntax checking to use Pry's trick (#38)
- [x] Get rid of --start-line and --end-line and instead have maybe --show-lines, a comma-separated array of lines to display output on (e.g. I can't think of a start/end line use-case, but it makes sense to want to see the current line, but then show for multiple cursors or where a user has marked in their editor)

### Other
- [x] Order frog stickers #14 

### Descoped

- Add a changelog (I added one, but didn't keep it up)
- Get it working on JRuby and Rbx (already put a lot of work into this, but a bug in current version of JRuby, and inability to install Rbx due to not having llvm are preventing me from getting it at the moment -- actually, I might try again, [this](https://twitter.com/rubinius/status/556657990682816512) worked for me)
- Use custom evaluators to support [safe mode](https://github.com/JoshCheek/seeing_is_believing/tree/safe-mode) (integration with [eval_in](http://rubygems.org/gems/eval_in)) (I no longer intend to do this 17db7e9)
- Expose ability to provide custom evaluators. (I only need one now. If anyone else needs one, they can ask me to do this. It shouldn't be hard, but don't see the need for the indirection at present.
- auto-record rescued exceptions (seemed like a lot of work without an obvious benefit)
- Track, for each line, what kind of obj it's recording (e.g. method def/literal/etc) and provide an interface for the user to specify what they would like to see. (going to have to wait until the next version, it's just going to take a lot of effort)
- A hybrid chunk/file line aligner that tries to line everything up for the whole file, but will discard outliers that are fucking it up. (might still do this one)
- Would be nice to find a way to deal with Atom identifying the file change too quickly. (yeah, idk what it would be)
- Would be nice to bundle a ruby executable with the editor integrations so newbies can just install with the editor's package manager instead of having to configure everything. (Traveling Ruby was what I was thinking, but it doesn't support Windows)

**Comment by JoshCheek** [comment]
V3 is released.
